version: '2'

services:
  jenkins:
    image: yantrashala/simpleci
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/jenkins_volume:/opt/jenkins
  
  template-creation:
    image: yantrashala/simpleci-template-creation
    ports:
      - '8000:8000'
    volumes:
      - /var/jenkins_volume:/opt/jenkins
